## Load the Saved Datasets

In [6]:
import pandas as pd
import numpy as np

In [7]:
cancer_data=pd.read_csv(r'F:\Cancer AI Analyst\data\structured\processed\cancer_cleaned.csv')
cancer_data.head()

,Age,Gender,Country_Region,Year,Genetic_Risk,Air_Pollution,Alcohol_Use,Smoking,Obesity_Level,Cancer_Type,Cancer_Stage,Treatment_Cost_USD,Survival_Years,Target_Severity_Score
0,71,Male,UK,2021,6.4,2.8,9.5,0.9,8.7,Lung,Stage III,62913.44,5.9,4.92
1,34,Male,China,2021,1.3,4.5,3.7,3.9,6.3,Leukemia,Stage 0,12573.41,4.7,4.65
2,80,Male,Pakistan,2023,7.4,7.9,2.4,4.7,0.1,Breast,Stage II,6984.33,7.1,5.84
3,40,Male,UK,2015,1.7,2.9,4.8,3.5,2.7,Colon,Stage I,67446.25,1.6,3.12
4,43,Female,Brazil,2017,5.1,2.8,2.3,6.7,0.5,Skin,Stage III,77977.12,2.9,3.62

## Separate Numerical and Categorical Columns

In [8]:
numerical_cols=cancer_data.select_dtypes(
    include=["int64", "float64"]
).columns
categorical_cols=cancer_data.select_dtypes(
    include=["object"]
).columns
print("Numerical Columns:")
print(numerical_cols)
print("\nCategorical Columns:")
print(categorical_cols)

Numerical Columns:
Index(['Age', 'Year', 'Genetic_Risk', 'Air_Pollution', 'Alcohol_Use',
       'Smoking', 'Obesity_Level', 'Treatment_Cost_USD', 'Survival_Years',
       'Target_Severity_Score'],
      dtype='object')

Categorical Columns:
Index(['Gender', 'Country_Region', 'Cancer_Type', 'Cancer_Stage'], dtype='object')

## Descriptive Statistics

In [9]:
cancer_data[numerical_cols].describe().T

,count,mean,std,min,25%,50%,75%,max
Age,50000.0,54.421540,20.224451,20.00,37.000,54.00,72.00,89.00
Year,50000.0,2019.480520,2.871485,2015.00,2017.000,2019.00,2022.00,2024.00
Genetic_Risk,50000.0,5.001698,2.885773,0.00,2.500,5.00,7.50,10.00
Air_Pollution,50000.0,5.010126,2.888399,0.00,2.500,5.00,7.50,10.00
Alcohol_Use,50000.0,5.010880,2.888769,0.00,2.500,5.00,7.50,10.00
Smoking,50000.0,4.989826,2.881579,0.00,2.500,5.00,7.50,10.00
Obesity_Level,50000.0,4.991176,2.894504,0.00,2.500,5.00,7.50,10.00
Treatment_Cost_USD,50000.0,52467.298239,27363.229379,5000.05,28686.225,52474.31,76232.72,99999.84
Survival_Years,50000.0,5.006462,2.883335,0.00,2.500,5.00,7.50,10.00
Target_Severity_Score,50000.0,4.951207,1.199677,0.90,4.120,4.95,5.78,9.16

## Central Tendency Analysis

In [10]:
central_tendency=pd.DataFrame({
    "Mean": cancer_data[numerical_cols].mean(),
    "Median": cancer_data[numerical_cols].median(),
    "Mode": cancer_data[numerical_cols].mode().iloc[0]
})
central_tendency

                               Mean    Median     Mode
Age                       54.421540     54.00    77.00
Year                    2019.480520   2019.00  2016.00
Genetic_Risk               5.001698      5.00     8.80
Air_Pollution              5.010126      5.00     0.80
Alcohol_Use                5.010880      5.00     6.80
Smoking                    4.989826      5.00     2.20
Obesity_Level              4.991176      5.00     8.30
Treatment_Cost_USD     52467.298239  52474.31  7807.18
Survival_Years             5.006462      5.00     4.60
Target_Severity_Score      4.951207      4.95     4.99

## Dispersion Analysis

In [11]:
dispersion=pd.DataFrame({
    "Range": cancer_data[numerical_cols].max()
             - cancer_data[numerical_cols].min(),
    "Variance": cancer_data[numerical_cols].var(),
    "Std_Dev": cancer_data[numerical_cols].std()
})
dispersion.sort_values(
    by="Std_Dev",
    ascending=False
)

                          Range      Variance       Std_Dev
Treatment_Cost_USD     94999.79  7.487463e+08  27363.229379
Age                       69.00  4.090284e+02     20.224451
Obesity_Level             10.00  8.378154e+00      2.894504
Alcohol_Use               10.00  8.344985e+00      2.888769
Air_Pollution             10.00  8.342851e+00      2.888399
Genetic_Risk              10.00  8.327683e+00      2.885773
Survival_Years            10.00  8.313624e+00      2.883335
Smoking                   10.00  8.303496e+00      2.881579
Year                       9.00  8.245425e+00      2.871485
Target_Severity_Score      8.26  1.439224e+00      1.199677

## Skewness Analysis

In [12]:
skewness=cancer_data[numerical_cols].skew()
skewness.sort_values(
    ascending=False
)

Year                     0.011239
Smoking                  0.005872
Treatment_Cost_USD       0.004064
Survival_Years           0.003023
Age                      0.002872
Air_Pollution            0.002335
Obesity_Level            0.001919
Target_Severity_Score   -0.002453
Genetic_Risk            -0.002950
Alcohol_Use             -0.008015
dtype: float64

## Kurtosis Analysis

In [13]:
kurtosis=cancer_data[numerical_cols].kurtosis()
kurtosis.sort_values(
    ascending=False
)

Target_Severity_Score   -0.233507
Survival_Years          -1.192835
Air_Pollution           -1.193445
Treatment_Cost_USD      -1.196421
Smoking                 -1.197331
Genetic_Risk            -1.197911
Alcohol_Use             -1.203391
Obesity_Level           -1.204567
Age                     -1.208371
Year                    -1.221254
dtype: float64

## Categorical Analysis

In [14]:
for col in categorical_cols:
    print("\n" + "="*50)
    print(col)
    print(
        cancer_data[col].value_counts()
    )

==================================================
Gender
Gender
Male      16796
Female    16709
Other     16495
Name: count, dtype: int64

==================================================
Country_Region
Country_Region
Australia    5092
UK           5060
USA          5060
India        5040
Germany      5024
Russia       5017
Brazil       5004
Pakistan     4926
China        4913
Canada       4864
Name: count, dtype: int64

==================================================
Cancer_Type
Cancer_Type
Colon       6376
Prostate    6308
Leukemia    6266
Liver       6249
Skin        6231
Cervical    6222
Breast      6189
Lung        6159
Name: count, dtype: int64

==================================================
Cancer_Stage
Cancer_Stage
Stage II     10124
Stage I      10046
Stage III    10008
Stage IV      9933
Stage 0       9889
Name: count, dtype: int64

## Correlation Analysis

In [15]:
correlation_matrix=cancer_data[
    numerical_cols
].corr()
correlation_matrix

,Age,Year,Genetic_Risk,Air_Pollution,Alcohol_Use,Smoking,Obesity_Level,Treatment_Cost_USD,Survival_Years,Target_Severity_Score
Age,1.000000,-0.002505,0.002229,0.001101,-0.004130,0.001734,-0.002706,0.003591,-0.000147,-0.001481
Year,-0.002505,1.000000,0.009942,0.000649,0.001934,-0.006209,-0.002441,0.000061,0.000018,0.002109
Genetic_Risk,0.002229,0.009942,1.000000,-0.004492,-0.002558,-0.003718,0.003522,-0.002365,0.001708,0.478700
Air_Pollution,0.001101,0.000649,-0.004492,1.000000,0.003511,0.003549,0.006507,-0.007566,0.000893,0.366963
Alcohol_Use,-0.004130,0.001934,-0.002558,0.003511,1.000000,-0.002938,0.007425,-0.003608,-0.000527,0.363250
Smoking,0.001734,-0.006209,-0.003718,0.003549,-0.002938,1.000000,0.005828,-0.009169,0.001371,0.484420
Obesity_Level,-0.002706,-0.002441,0.003522,0.006507,0.007425,0.005828,1.000000,-0.001251,0.009771,0.251366
Treatment_Cost_USD,0.003591,0.000061,-0.002365,-0.007566,-0.003608,-0.009169,-0.001251,1.000000,-0.000429,-0.466058
Survival_Years,-0.000147,0.000018,0.001708,0.000893,-0.000527,0.001371,0.009771,-0.000429,1.000000,0.004161
Target_Severity_Score,-0.001481,0.002109,0.478700,0.366963,0.363250,0.484420,0.251366,-0.466058,0.004161,1.000000

## Target-Based Correlation

In [16]:
correlation_matrix[
    "Target_Severity_Score"
].sort_values(
    ascending=False
)

Target_Severity_Score    1.000000
Smoking                  0.484420
Genetic_Risk             0.478700
Air_Pollution            0.366963
Alcohol_Use              0.363250
Obesity_Level            0.251366
Survival_Years           0.004161
Year                     0.002109
Age                     -0.001481
Treatment_Cost_USD      -0.466058
Name: Target_Severity_Score, dtype: float64