In [1]:
import pandas as pd
import numpy as np
cancer_data=pd.read_csv(
    "../data/structured/processed/cancer_feature_engineered.csv"
)
cancer_data.head()

,Age,Gender,Country_Region,Year,Genetic_Risk,Air_Pollution,Alcohol_Use,Smoking,Obesity_Level,Cancer_Type,Cancer_Stage,Treatment_Cost_USD,Survival_Years,Target_Severity_Score,Lifestyle_Risk_Score,Overall_Risk_Score,Age_Group,Survival_Category,Cost_Category,Stage_Severity
0,71,Male,UK,2021,6.4,2.8,9.5,0.9,8.7,Lung,Stage III,62913.44,5.9,4.92,21.9,28.3,Senior,High,High,3.0
1,34,Male,China,2021,1.3,4.5,3.7,3.9,6.3,Leukemia,Stage 0,12573.41,4.7,4.65,18.4,19.7,Young,Medium,Low,NaN
2,80,Male,Pakistan,2023,7.4,7.9,2.4,4.7,0.1,Breast,Stage II,6984.33,7.1,5.84,15.1,22.5,Senior,High,Low,2.0
3,40,Male,UK,2015,1.7,2.9,4.8,3.5,2.7,Colon,Stage I,67446.25,1.6,3.12,13.9,15.6,Young,Low,High,1.0
4,43,Female,Brazil,2017,5.1,2.8,2.3,6.7,0.5,Skin,Stage III,77977.12,2.9,3.62,12.3,17.4,Middle_Aged,Medium,Very_High,3.0

In [2]:
cancer_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Age                    50000 non-null  int64
 1   Gender                 50000 non-null  object
 2   Country_Region         50000 non-null  object
 3   Year                   50000 non-null  int64
 4   Genetic_Risk           50000 non-null  float64
 5   Air_Pollution          50000 non-null  float64
 6   Alcohol_Use            50000 non-null  float64
 7   Smoking                50000 non-null  float64
 8   Obesity_Level          50000 non-null  float64
 9   Cancer_Type            50000 non-null  object
 10  Cancer_Stage           50000 non-null  object
 11  Treatment_Cost_USD     50000 non-null  float64
 12  Survival_Years         50000 non-null  float64
 13  Target_Severity_Score  50000 non-null  float64
 14  Lifestyle_Risk_Score   50000 non-null  float64
 15  Overall_Risk_Score     50000 non-null  float64
 16  Age_Group              50000 non-null  object
 17  Survival_Category      49751 non-null  object
 18  Cost_Category          50000 non-null  object
 19  Stage_Severity         40111 non-null  float64
dtypes: float64(11), int64(2), object(7)
memory usage: 7.6+ MB

## Separate X and y target is Target_Severity_score

In [3]:
X=cancer_data.drop(
    columns=["Target_Severity_Score"]
)
y=cancer_data["Target_Severity_Score"]

## Identify Categorical Columns

In [4]:
categorical_cols=X.select_dtypes(
    include=["object","category"]
).columns
categorical_cols

Index(['Gender', 'Country_Region', 'Cancer_Type', 'Cancer_Stage', 'Age_Group',
       'Survival_Category', 'Cost_Category'],
      dtype='object')

## One-Hot Encoding

In [5]:
X_encoded=pd.get_dummies(
    X,
    columns=categorical_cols,
    drop_first=True
)

In [6]:
X_encoded.shape

(50000, 42)

## Feature Scaling

In [8]:
from sklearn.preprocessing import StandardScaler

In [9]:
scalar=StandardScaler()
X_scaled=scalar.fit_transform(X_encoded)

In [10]:
import pandas as pd
X_scaled=pd.DataFrame(
    X_scaled,
    columns=X_encoded.columns
)
X_scaled.head()

,Age,Year,Genetic_Risk,Air_Pollution,Alcohol_Use,Smoking,Obesity_Level,Treatment_Cost_USD,Survival_Years,Lifestyle_Risk_Score,...,Cancer_Stage_Stage III,Cancer_Stage_Stage IV,Age_Group_Middle_Aged,Age_Group_Senior,Age_Group_Young,Survival_Category_Low,Survival_Category_Medium,Cost_Category_Low,Cost_Category_Medium,Cost_Category_Very_High
0,0.819732,0.529167,0.484555,-0.765181,1.554006,-1.419315,1.281346,0.381762,0.309900,0.326620,...,1.999001,-0.497905,-0.628623,1.577792,-0.658678,-0.496466,-0.661082,-0.577350,-0.57735,-0.577350
1,-1.009755,0.529167,-1.282754,-0.176614,-0.453790,-0.378208,0.452180,-1.457952,-0.106288,-0.275685,...,-0.500250,-0.497905,-0.628623,-0.633797,1.518193,-0.496466,1.512672,1.732051,-0.57735,-0.577350
2,1.264742,1.225678,0.831086,1.000521,-0.903813,-0.100580,-1.689832,-1.662210,0.726089,-0.843574,...,-0.500250,-0.497905,-0.628623,1.577792,-0.658678,-0.496466,-0.661082,1.732051,-0.57735,-0.577350
3,-0.713082,-1.560365,-1.144141,-0.730559,-0.073001,-0.517022,-0.791569,0.547417,-1.181443,-1.050078,...,-0.500250,-0.497905,-0.628623,-0.633797,1.518193,2.014236,-0.661082,-0.577350,-0.57735,-0.577350
4,-0.564745,-0.863854,0.034065,-0.765181,-0.938430,0.593491,-1.551637,0.932276,-0.730572,-1.325418,...,1.999001,-0.497905,1.590778,-0.633797,-0.658678,-0.496466,1.512672,-0.577350,-0.57735,1.732051

## Train-Test Split

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train, X_test, y_train, y_test=train_test_split(
    X_scaled,
    y,
    test_size=0.2,
    random_state=42
)

In [13]:
print(X_train.shape)
print(X_test.shape)

(40000, 42)
(10000, 42)

## Save The Processed Data

In [14]:
X_scaled.to_csv(
    "../data/structured/processed/X_preprocessed.csv",
    index=False
)

In [15]:
y.to_csv(
    "../data/structured/processed/y_target.csv",
    index=False
)

In [17]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(X_train)
joblib.dump(
    scaler,
    "../models/scaler.pkl"
)

['../models/scaler.pkl']

## Save the Train-Test Split

In [18]:
joblib.dump(
    (X_train, X_test, y_train, y_test),
    "../models/train_test_split.pkl"
)

['../models/train_test_split.pkl']